-- ========================================================
-- Módulo novo: Áudios (banco de clipes por médico, compartilhado por empresa)
-- ========================================================
-- Mesmo modelo já em produção pra exercises/topics/virtues/medias/books:
-- can_view_scoped_content(company_id, patient_id) cobre admin, dono e
-- paciente/colega da mesma empresa sem precisar de função dedicada nem de
-- liberação por item (patient_audio_flags fica pra uma fase futura, se
-- fizer falta). Storage reaproveita o bucket media_uploads já existente,
-- só com uma subpasta nova (audio-clips) — sem migration de Storage.

create table if not exists public.audio_clips (
    id bigint generated by default as identity primary key,
    title text not null,
    audio_url text not null,
    doctor_user_id uuid references auth.users(id),
    company_id uuid references public.companies(id),
    patient_id uuid references public.patients(id) on delete restrict,
    color_class text,
    visible boolean not null default true,
    created_at timestamptz not null default now()
);
alter table public.audio_clips enable row level security;

create policy "Leitura pública de audio_clips" on public.audio_clips
    for select using (public.can_view_scoped_content(company_id, patient_id));

create policy "Escrita de médicos em audio_clips do próprio banco" on public.audio_clips
    for all to authenticated
    using (public.is_admin() or (doctor_user_id is not null and doctor_user_id = auth.uid()))
    with check (public.is_admin() or (doctor_user_id is not null and doctor_user_id = auth.uid()));

create policy "Escrita de médicos no banco da empresa em audio_clips" on public.audio_clips
    for all to authenticated
    using (doctor_user_id is not null and patient_id is null and company_id is not null and company_id = public.user_company_id())
    with check (doctor_user_id is not null and patient_id is null and company_id is not null and company_id = public.user_company_id());
