-- ========================================================
-- Lembretes do médico para os pacientes
-- ========================================================
-- O médico escolhe um ou vários pacientes em "Meus Pacientes" e envia um
-- lembrete na hora: mensagem padrão ("hora de praticar") com um recado
-- opcional. O paciente recebe por e-mail (função notify-users) e também vê
-- o lembrete ao abrir o app, até clicar em "Entendi".
--
-- Uma linha por paciente lembrado. Quem grava é a função notify-users (chave
-- de serviço), depois de conferir que quem enviou é médico do paciente (ou
-- colega da mesma empresa) ou admin/editor — por isso não há regra de
-- insert para usuários.
--
-- Acesso:
--   - paciente: lê os próprios lembretes e marca como lido (read_at);
--   - médico: lê os lembretes dos seus pacientes (is_doctor_of_patient);
--   - admin: lê todos.

create table if not exists public.patient_reminders (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    patient_id uuid not null references public.patients(id) on delete cascade,
    sender_user_id uuid references auth.users(id) on delete set null,
    sender_name text,
    message text check (message is null or char_length(message) <= 500),
    read_at timestamptz
);

create index if not exists patient_reminders_patient_idx
    on public.patient_reminders (patient_id, created_at desc);

alter table public.patient_reminders enable row level security;

drop policy if exists "Paciente lê os próprios lembretes" on public.patient_reminders;
create policy "Paciente lê os próprios lembretes" on public.patient_reminders
    for select to authenticated
    using (patient_id = public.current_patient_id());

drop policy if exists "Paciente marca os próprios lembretes como lidos" on public.patient_reminders;
create policy "Paciente marca os próprios lembretes como lidos" on public.patient_reminders
    for update to authenticated
    using (patient_id = public.current_patient_id())
    with check (patient_id = public.current_patient_id());

drop policy if exists "Médico lê lembretes dos seus pacientes" on public.patient_reminders;
create policy "Médico lê lembretes dos seus pacientes" on public.patient_reminders
    for select to authenticated
    using (public.is_doctor_of_patient(patient_id));

drop policy if exists "Admin lê todos os lembretes" on public.patient_reminders;
create policy "Admin lê todos os lembretes" on public.patient_reminders
    for select to authenticated
    using (public.is_admin());

grant select on public.patient_reminders to authenticated;
-- O paciente só consegue mudar read_at (as outras colunas ficam fora do grant).
grant update (read_at) on public.patient_reminders to authenticated;
